---

- name: "Installing PHP"
  yum:
    name: "{{ item }}"
    state: "present"
  with_items:
    - php
    - php-mysql
    - php-fpm
- name: "Fixing php.ini"
  template:
    src=php.ini.j2
    dest="/etc/php.ini"
  notify:
    - restart-php
- name: "Fixing PHP-FPM"
  template:
    src=php-fpm.conf.j2
    dest="/etc/php-fpm.d/www.conf"
  notify:
    - restart-php
